apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orders-postgresql
  namespace: default
  labels:
    app: orders
spec:
  selector:
    matchLabels:
      app: orders
  serviceName: "orders-postgresql"
  replicas: 1
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: postgresql
        image: public.ecr.aws/docker/library/postgres:13
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          name: postgresql
          protocol: TCP
        env:
        - name: POSTGRES_DB
          value: orders
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: RETAIL_ORDERS_PERSISTENCE_USERNAME
              name: orders-db-secret
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: RETAIL_ORDERS_PERSISTENCE_PASSWORD
              name: orders-db-secret
        - name: PGDATA
          value: /data/pgdata
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        emptyDir: {} # replace with PVC if persistence enabled
--- 
apiVersion: v1
kind: Service
metadata:
  name: orders-postgresql
  namespace: default
  labels:
    app: orders
spec:
  type: ClusterIP
  selector:
    app: orders-postgresql
  ports:
    - port: 5432
      targetPort: postgresql
      name: postgresql