apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orders-rabbitmq
  labels:
    app: orders
spec:
  replicas: 1
  serviceName: orders-rabbitmq
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: rabbitmq
          image: public.ecr.aws/docker/library/rabbitmq:3.8-management
          imagePullPolicy: IfNotPresent
          ports:
          - name: amqp
            containerPort: 5672
            protocol: TCP
          - name: http
            containerPort: 15672
            protocol: TCP
          volumeMounts:
          - name: data
            mountPath: "/var/lib/rabbitmq/mnesia"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "10Gi"
--- 
apiVersion: v1
kind: Service
metadata:
  name: orders-rabbitmq
  namespace: default
  labels:
    app: orders
spec:
  type: ClusterIP
  selector:
    app: orders-rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
      protocol: TCP
    - name: http
      port: 15672
      targetPort: http
      protocol: TCP