apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: default
type: Opaque
data:
  SPRING_RABBITMQ_USERNAME: cmFiYml0 # base64 of "rabbit"
  SPRING_RABBITMQ_PASSWORD: cGFzc3dvcmQ= # base64 of "password"

