---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts-dynamodb
  namespace: default
  labels:
    app.kubernetes.io/name: carts-dynamodb
    app.kubernetes.io/instance: carts
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: carts-dynamodb
      app.kubernetes.io/instance: carts
  template:
    metadata:
      labels:
        app.kubernetes.io/name: carts-dynamodb
        app.kubernetes.io/instance: carts
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: dynamodb
        image: public.ecr.aws/aws-dynamodb-local/aws-dynamodb-local:1.25.1
        imagePullPolicy: IfNotPresent
        ports:
        - name: dynamodb 
          containerPort: 8000
          protocol: TCP
--- 
apiVersion: v1
kind: Service
metadata:
  name: carts-dynamodb
  labels:
    app.kubernetes.io/name: carts-dynamodb
    app.kubernetes.io/instance: carts
spec:
  type: ClusterIP
  ports:
  - name: dynamodb
    port: 8000
    targetPort: dynamodb
    protocol: TCP
  selector:
    app.kubernetes.io/name: carts-dynamodb
    app.kubernetes.io/instance: carts
    