apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: carts
  labels:
    app.kubernetes.io/name: carts
    app.kubernetes.io/instance: carts
spec:
  minAvailable: 2
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: carts
      app.kubernetes.io/instance: carts