--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      serviceAccountName: checkout-sa
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: checkout
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: public.ecr.aws/aws-containers/retail-store-sample-checkout:1.3.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http 
          protocol: TCP
        envFrom:
        - configMapRef:
            name: checkout-config
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        resources:
          requests:
            cpu: "128m"
            memory: "256Mi"
          limits:
            memory: "256Mi"
            cpu: "512m"
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
      - name: tmp-volume
        emptyDir:
          medium: Memory
--- 
apiVersion: v1
kind: Service
metadata:
  name: checkout
  namespace: default
  labels:
    app: checkout
spec:
  type: ClusterIP
  selector:
    app: checkout
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP