---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-redis
  namespace: default
  labels:
    app: checkout-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout-redis
  template:
    metadata:
      labels:
        app: checkout-redis
    spec:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: redis 
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: public.ecr.aws/docker/library/redis:6.0-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: redis 
          containerPort: 6379
          protocol: TCP
        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 6379
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 6379
        resources:
         limits:
           memory: 256Mi
           cpu: 125m
         requests:
           cpu: 70m
           memory: 200Mi
        volumeMounts:
        - mountPath: /data
          name: redis-data
      
      volumes:
      - name: redis-data
        emptyDir: {}
--- 
apiVersion: v1
kind: Service
metadata:
  name: checkout-redis
  namespace: default
  labels:
    app: checkout-redis
spec:
  type: ClusterIP
  selector:
    app: checkout-redis
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
