apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
  namespace: default
data:
  RETAIL_UI_ENDPOINTS_CATALOG: http://retail-store-catalog:80
  RETAIL_UI_ENDPOINTS_CARTS: http://retail-store-cart-carts:80
  RETAIL_UI_ENDPOINTS_CHECKOUT: http://retail-store-checkout:80
  RETAIL_UI_ENDPOINTS_ORDERS: http://retail-store-orders:80
  